[package]
name = "envparse"
version = "0.0.1"
edition = "2021"
authors = ["Thom Chiovoloni <thom@shift.click>"]
readme = "README.md"
description = "Parse compile-time environment variables into `const`s"
rust-version = "1.82.0"

[dev-dependencies]
compiletest_rs = "0.11.1"
