[package]
name = "envparse"
version = "0.0.1"
edition = "2021"
authors = ["Thom Chiovoloni <thom@shift.click>"]
readme = "README.md"
description = "Parse compile-time environment variables into `const`s"

[features]
const_panic = []

[dependencies]
